### ISSUE TITLE
[bug] Crash on load 

### ISSUE THREAD

**Issue by CKY-** [eutro/FramedCompactDrawers#11]
5/27/2022  StorageDrawers-1.18.2-10.2.1 update  causes crash on load 

here is the crash report 

https://crashy.net/5l9GMlo3ulyaKGPCUjv1

**Comment by eutro** [comment]
Should be fixed in 50433d585e082734a2d3e73b2793b69e4f0f8bcc. The release can be found [here](https://www.curseforge.com/minecraft/mc-mods/framed-compacting-drawers/files/3808242) (as soon as it's approved).
