### ISSUE TITLE
Void upgrade bug

### ISSUE THREAD

**Issue by LindaJuffermans** [eutro/FramedCompactDrawers#12]
I've setup 2x2 drawers for Mystical Agriculture seeds. 3 slots for the produce and 1 slot for the seeds. I've added a storage upgrade V (32x) and a void upgrade.

I found that the produce got voided if the first slot was filled to the max, ignoring the other two slots (the single stack I put there myself):
![image](https://user-images.githubusercontent.com/31929183/171571916-e98b99c4-9a97-49d8-89d0-99dcce01ca53.png)

framedcompactdrawers-1.16-2.2.1.jar
Minecraft 1.16.5
Forge 36.2.34

**Comment by eutro** [comment]
Does this happen with regular drawers too? This mod doesn't (in theory) touch any of the item handling code and just inherits it from regular Storage Drawers.

**Comment by LindaJuffermans** [comment]
It does, I should have tested that first.

Raised https://github.com/jaquadro/StorageDrawers/issues/1023
