### ISSUE TITLE
items compacted in a 2x2 and other 4 item compacts

### ISSUE THREAD

**Issue by billjk2013** [eutro/FramedCompactDrawers#21]
2x2 example from {ex deorum [ore chunks]}
![2024-06-05_09 04 43](https://github.com/eutro/FramedCompactDrawers/assets/133094322/51322c90-3e7c-4bf4-9c65-e2f6b8aabe0a)
![2024-06-05_09 16 09](https://github.com/eutro/FramedCompactDrawers/assets/133094322/701b72d5-82e6-454b-b5f5-69fc91740634)
![2024-06-05_09 15 55](https://github.com/eutro/FramedCompactDrawers/assets/133094322/4bd2e061-1708-4da0-be74-20226379d35b)

other  item compact example from {forbidden & arcanus}
![2024-06-05_09 05 52](https://github.com/eutro/FramedCompactDrawers/assets/133094322/9f97a09f-c19b-4d5f-a027-1da2dd8e76d6)
![2024-06-05_09 16 28](https://github.com/eutro/FramedCompactDrawers/assets/133094322/9c6ae8b6-09b9-4a86-8f1d-3dcd52a5b2f7)
![2024-06-05_09 17 08](https://github.com/eutro/FramedCompactDrawers/assets/133094322/e99bb64f-ec6d-4c6c-9a9d-271fb0406417)

**Comment by eutro** [comment]
The compaction logic is part of the base [Storage Drawers](https://github.com/jaquadro/StorageDrawers) mod. It has some detection for combination recipes, including 2x2 recipes ([code](https://github.com/jaquadro/StorageDrawers/blob/62cd5561b10a41ecc647d4b21ba49b785c302dc9/src/main/java/com/jaquadro/minecraft/storagedrawers/util/CompactingHelper.java)), though they require bidirectional (`Upper -> 4 x Lower` _and_ `2x2 of Lower -> Upper`) recipes as far as I can see. You can add extra compacting rules manually in the config, it should be `compactingRules` in the common config file of Storage Drawers ([code](https://github.com/jaquadro/StorageDrawers/blob/62cd5561b10a41ecc647d4b21ba49b785c302dc9/src/main/java/com/jaquadro/minecraft/storagedrawers/config/CommonConfig.java#L77)).
